### Tải extension REST Client rồi ấn send request nó sẽ trả ra response cho mình

### GET all categories - lấy toàn bộ danh mục
GET http://localhost:8080/api/categories
Accept: application/json

###

### GET products by category - danh mục id=1 (Áo thun)
GET http://localhost:8080/api/products/category/1
Accept: application/json

###

### GET products by category - danh mục id=2 (Quần jean)
GET http://localhost:8080/api/products/category/2
Accept: application/json

###

### GET products by category - danh mục id=3 (Váy)
GET http://localhost:8080/api/products/category/3
Accept: application/json

###

### GET products by category - danh mục id=4 (Phụ kiện)
GET http://localhost:8080/api/products/category/4
Accept: application/json

###

### GET products by category - id không tồn tại (expect data=[])
GET http://localhost:8080/api/products/category/9999
Accept: application/json

###
